name: Build and Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8.10]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Set up Python ${{ matrix.python }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: "Cache Python dependencies"
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-${{ matrix.python }}-pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python }}-pip-
      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          pip install -r requirements-dev.txt  

  test-pruning:
    needs: build
    name: Filter pruning
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.build.outputs }} 
          python -m pytest tests/pruner